/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dadce11c-dd92-4073-a03f-91f086b6c7a7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NBJYY9ZCg",
    "aws_user_pools_web_client_id": "1pdndscdl7vtir53j8ama5jen6",
    "oauth": {}
};


export default awsmobile;
